name: Update Releases
on:
  release:
    types: [published]
    
jobs:
  build_asset:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: ls -l
      - uses: actions/checkout@v3
      - run: pwd
      - run: ls -l
      - run: gh release upload ${{ github.event.release.tag_name }} testfile.txt
        env:
          GH_TOKEN: ${{ github.token }}
