name: Update Releases
on:
  release:
    types: [published]
    
jobs:
  build_asset:
    runs-on: ubuntu-latest
    steps:
      #- uses: actions/checkout@v3
      - run: gh release upload ${{ github.event.tag_name }} testfile.txt
